"""initial_schema

Revision ID: fe5793facbbb
Revises: 
Create Date: 2026-05-20 18:51:25.061343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe5793facbbb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('osint_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_symbols', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('summary', sa.String(length=2000), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=16), nullable=True),
    sa.Column('entities', sa.Text(), nullable=True),
    sa.Column('topics', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_osint_articles_id'), 'osint_articles', ['id'], unique=False)
    op.create_index(op.f('ix_osint_articles_source'), 'osint_articles', ['source'], unique=False)
    op.drop_index(op.f('ix_chain_data_chain_name'), table_name='chain_data')
    op.drop_index(op.f('ix_chain_data_id'), table_name='chain_data')
    op.drop_table('chain_data')
    op.add_column('asset_chain_snapshots', sa.Column('price_coingecko', sa.Float(), nullable=True))
    op.add_column('asset_chain_snapshots', sa.Column('price_dexscreener', sa.Float(), nullable=True))
    op.add_column('asset_chain_snapshots', sa.Column('market_cap', sa.Float(), nullable=True))
    op.add_column('asset_chain_snapshots', sa.Column('volume_24h', sa.Float(), nullable=True))
    op.add_column('asset_chain_snapshots', sa.Column('total_liquidity_usd', sa.Float(), nullable=True))
    op.add_column('asset_chain_snapshots', sa.Column('top3_pool_share_pct', sa.Float(), nullable=True))
    op.add_column('asset_chain_snapshots', sa.Column('pool_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_chain_snapshots', 'pool_count')
    op.drop_column('asset_chain_snapshots', 'top3_pool_share_pct')
    op.drop_column('asset_chain_snapshots', 'total_liquidity_usd')
    op.drop_column('asset_chain_snapshots', 'volume_24h')
    op.drop_column('asset_chain_snapshots', 'market_cap')
    op.drop_column('asset_chain_snapshots', 'price_dexscreener')
    op.drop_column('asset_chain_snapshots', 'price_coingecko')
    op.create_table('chain_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chain_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('usdt_supply', sa.FLOAT(), nullable=False),
    sa.Column('tvl', sa.FLOAT(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('fetched_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('usdt_supply_prev_day', sa.FLOAT(), nullable=True),
    sa.Column('usdt_supply_prev_week', sa.FLOAT(), nullable=True),
    sa.Column('usdt_supply_prev_month', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chain_data_id'), 'chain_data', ['id'], unique=False)
    op.create_index(op.f('ix_chain_data_chain_name'), 'chain_data', ['chain_name'], unique=1)
    op.drop_index(op.f('ix_osint_articles_source'), table_name='osint_articles')
    op.drop_index(op.f('ix_osint_articles_id'), table_name='osint_articles')
    op.drop_table('osint_articles')
    # ### end Alembic commands ###
