"""Settings registry - contains all default settings definitions."""

from typing import Any, Dict

# Default settings registry - moved from providers/settings.py to reduce file size
_DEFAULT_SETTINGS: Dict[str, Dict[str, Any]] = {
    "cors_origins": {
        "label": "CORS Origins",
        "type": "str",
        "default": "http://localhost:3000,http://localhost",
        "group": "Security",
        "description": "Allowed CORS origins (comma-separated). Use '*' only for development.",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "feature_nlp_sentiment": {
        "label": "NLP Sentiment",
        "type": "bool",
        "default": True,
        "key_env": "ENABLE_NLP_SENTIMENT",
        "group": "Features",
        "description": "Enable NLP sentiment analysis (Settings is the source of truth; env is ignored in UI)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "asset_enable_overrides": {
        "label": "Asset Enable Overrides",
        "type": "str",
        "default": "{}",
        "group": "Data & Assets",
        "description": "JSON map of symbol→bool overrides on top of config/assets.json (e.g. {\"USDe\": true})",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "retention_asset_trend_snapshots_days": {
        "label": "Retention: Asset Trend Snapshots (days)",
        "type": "int",
        "default": 90,
        "min": 7,
        "max": 3650,
        "group": "Data & Assets",
        "description": "Days to retain asset_trend_snapshots (Timescale drop_chunks on PostgreSQL).",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "retention_chain_trend_snapshots_days": {
        "label": "Retention: Chain Trend Snapshots (days)",
        "type": "int",
        "default": 90,
        "min": 7,
        "max": 3650,
        "group": "Data & Assets",
        "description": "Days to retain chain_trend_snapshots (Timescale drop_chunks on PostgreSQL).",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "retention_signal_events_days": {
        "label": "Retention: Signal Events (days)",
        "type": "int",
        "default": 180,
        "min": 7,
        "max": 3650,
        "group": "Data & Assets",
        "description": "Days to retain signal_events rows.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "retention_osint_articles_days": {
        "label": "Retention: OSINT Articles (days)",
        "type": "int",
        "default": 30,
        "min": 7,
        "max": 3650,
        "group": "Data & Assets",
        "description": "Days to retain osint_articles rows.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "retention_funding_rate_snapshots_days": {
        "label": "Retention: Funding Rate Snapshots (days)",
        "type": "int",
        "default": 30,
        "min": 7,
        "max": 3650,
        "group": "Data & Assets",
        "description": "Days to retain funding_rate_snapshots rows.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "retention_yield_bearing_snapshots_days": {
        "label": "Retention: Yield-Bearing Snapshots (days)",
        "type": "int",
        "default": 180,
        "min": 7,
        "max": 3650,
        "group": "Data & Assets",
        "description": "Days to retain yield_bearing_snapshots rows.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "retention_collateral_snapshots_days": {
        "label": "Retention: Collateral Snapshots (days)",
        "type": "int",
        "default": 180,
        "min": 7,
        "max": 3650,
        "group": "Data & Assets",
        "description": "Days to retain collateral_snapshots rows.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "retention_whale_activity_snapshots_days": {
        "label": "Retention: Whale Activity Snapshots (days)",
        "type": "int",
        "default": 180,
        "min": 7,
        "max": 3650,
        "group": "Data & Assets",
        "description": "Days to retain whale_activity_snapshots rows.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "retention_web_search_snapshots_days": {
        "label": "Retention: web search cache",
        "type": "int",
        "default": 30,
        "min": 7,
        "max": 365,
        "group": "Data & Assets",
        "description": "Days to retain web_search_snapshots rows.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "retention_fiat_reserve_snapshots_days": {
        "label": "Retention: Fiat Reserve Snapshots (days)",
        "type": "int",
        "default": 730,
        "min": 30,
        "max": 3650,
        "group": "Data & Assets",
        "description": "Days to retain fiat_reserve_snapshots rows.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "retention_forecast_runs_days": {
        "label": "Retention: Forecast Runs (days)",
        "type": "int",
        "default": 180,
        "min": 7,
        "max": 3650,
        "group": "Data & Assets",
        "description": "Days to retain forecast_runs and cascade-delete forecast_points.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "retention_ai_narrative_history_days": {
        "label": "Retention: AI Narrative History (days)",
        "type": "int",
        "default": 90,
        "min": 7,
        "max": 3650,
        "group": "Data & Assets",
        "description": "Days to retain ai_narrative_history rows.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "retention_settings_audit_log_days": {
        "label": "Retention: Settings Audit Log (days)",
        "type": "int",
        "default": 365,
        "min": 30,
        "max": 3650,
        "group": "Data & Assets",
        "description": "Days to retain settings_audit_log rows.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "retention_source_usage_days": {
        "label": "Retention: Source Usage (days)",
        "type": "int",
        "default": 400,
        "min": 30,
        "max": 3650,
        "group": "Data & Assets",
        "description": "Days to retain source_usage rows.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "retention_ai_usage_days": {
        "label": "Retention: AI Usage (days)",
        "type": "int",
        "default": 400,
        "min": 30,
        "max": 3650,
        "group": "Data & Assets",
        "description": "Days to retain ai_usage rows.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "retention_fred_yields_days": {
        "label": "Retention: FRED Yields (DuckDB days)",
        "type": "int",
        "default": 730,
        "min": 30,
        "max": 3650,
        "group": "Data & Assets",
        "description": "Days to retain fred_yields rows in DuckDB mirror.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "llm_extract_cache_ttl": {
        "label": "LLM Extract Cache TTL",
        "type": "int",
        "default": 3600,
        "min": 60,
        "max": 86400,
        "group": "Cache",
        "description": "Cache TTL for LLM data extraction (seconds)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "anomaly_std_floor": {
        "label": "Anomaly Std Floor",
        "type": "float",
        "default": 0.01,
        "group": "Analysis",
        "description": "Minimum standard deviation floor for anomaly detection",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "anomaly_z_threshold_supply": {
        "label": "Anomaly Z Threshold (Supply)",
        "type": "float",
        "default": 3.5,
        "min": 1.0,
        "max": 10.0,
        "group": "Analysis",
        "description": "Z-score threshold for supply anomalies",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "anomaly_z_threshold_price": {
        "label": "Anomaly Z Threshold (Price)",
        "type": "float",
        "default": 2.5,
        "min": 1.0,
        "max": 10.0,
        "group": "Analysis",
        "description": "Z-score threshold for price anomalies",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "anomaly_z_threshold_depeg_index": {
        "label": "Anomaly Z Threshold (Depeg)",
        "type": "float",
        "default": 2.5,
        "min": 1.0,
        "max": 10.0,
        "group": "Analysis",
        "description": "Z-score threshold for depeg index anomalies",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "anomaly_z_threshold_concentration": {
        "label": "Anomaly Z Threshold (Concentration)",
        "type": "float",
        "default": 3.0,
        "min": 1.0,
        "max": 10.0,
        "group": "Analysis",
        "description": "Z-score threshold for concentration anomalies",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "anomaly_z_threshold_signal": {
        "label": "Anomaly Z Threshold (Signal)",
        "type": "float",
        "default": 3.0,
        "min": 1.0,
        "max": 10.0,
        "group": "Analysis",
        "description": "Z-score threshold for signal score anomalies",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "anomaly_z_threshold_cusum_supply": {
        "label": "Anomaly CUSUM Threshold (Supply)",
        "type": "float",
        "default": 3.0,
        "min": 1.0,
        "max": 10.0,
        "group": "Analysis",
        "description": "CUSUM threshold for supply change points",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "anomaly_z_threshold_cusum_depeg": {
        "label": "Anomaly CUSUM Threshold (Depeg)",
        "type": "float",
        "default": 3.0,
        "min": 1.0,
        "max": 10.0,
        "group": "Analysis",
        "description": "CUSUM threshold for depeg change points",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "anomaly_z_threshold_cusum_concentration": {
        "label": "Anomaly CUSUM Threshold (Concentration)",
        "type": "float",
        "default": 3.0,
        "min": 1.0,
        "max": 10.0,
        "group": "Analysis",
        "description": "CUSUM threshold for concentration change points",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "sentiment_max_articles_per_batch": {
        "label": "Sentiment Max Articles",
        "type": "int",
        "default": 10,
        "min": 10,
        "max": 200,
        "group": "Analysis",
        "description": "Max articles per sentiment batch",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "alert_smtp_host": {
        "label": "SMTP Host",
        "type": "str",
        "default": "",
        "key_env": "ALERT_SMTP_HOST",
        "group": "Notifications",
        "description": "SMTP server host",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "alert_smtp_port": {
        "label": "SMTP Port",
        "type": "int",
        "default": 587,
        "min": 1,
        "max": 65535,
        "group": "Notifications",
        "description": "SMTP server port",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "alert_smtp_user": {
        "label": "SMTP User",
        "type": "str",
        "default": "",
        "key_env": "ALERT_SMTP_USER",
        "group": "Notifications",
        "description": "SMTP username",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "alert_smtp_pass": {
        "label": "SMTP Password",
        "type": "secret",
        "default": "",
        "key_env": "ALERT_SMTP_PASS",
        "secret": True,
        "group": "Notifications",
        "description": "SMTP password",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "allow_backfill": {
        "label": "Allow Backfill",
        "type": "bool",
        "default": False,
        "group": "Data Collection",
        "description": "Allow historical data backfill",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "enable_redis_cache": {
        "label": "Enable Redis Cache",
        "type": "bool",
        "default": True,
        "key_env": "ENABLE_REDIS_CACHE",
        "group": "Cache",
        "description": "Enable Redis caching when REDIS_URL is set (default on for Compose).",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "enable_chainlink": {
        "label": "Enable Chainlink",
        "type": "bool",
        "default": False,
        "key_env": "ENABLE_CHAINLINK",
        "group": "Data Collection",
        "description": "Enable Chainlink oracle data",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "enable_dynamic_chains": {
        "label": "Enable Dynamic Chains",
        "type": "bool",
        "default": False,
        "group": "Features",
        "description": "Enable dynamic chain discovery",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "provider_defillama": {
        "label": "DefiLlama",
        "type": "bool",
        "default": True,
        "always_active": True,
        "group": "Data Providers",
        "description": "Enable DefiLlama API for stablecoin metrics",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "provider_dexscreener": {
        "label": "DexScreener",
        "type": "bool",
        "default": True,
        "always_active": True,
        "group": "Data Providers",
        "description": "Enable DexScreener API for DEX pool data",
        "requires_restart": False,
        "affects_rate_limits": True,
        "rate_limit_rpm": 120,  # Increased from 60 to 120
        "warning_threshold": 0.8,
    },
    "provider_coingecko": {
        "label": "CoinGecko",
        "type": "bool",
        "default": True,
        "always_active": True,
        "group": "Data Providers",
        "description": "Enable CoinGecko API for price data",
        "requires_restart": False,
        "affects_rate_limits": True,
        "rate_limit_rpm": 100,  # Increased from 50 to 100
        "warning_threshold": 0.8,
    },
    "provider_moralis": {
        "label": "Moralis",
        "type": "bool",
        "default": False,
        "key_env": "MORALIS_API_KEY",
        "group": "Data Providers",
        "description": "Enable Moralis API for holder concentration and whale transfers (40K CU/day free)",
        "requires_restart": False,
        "affects_rate_limits": True,
        "rate_limit_rpm": 20,
        "warning_threshold": 0.8,
    },
    "provider_thegraph": {
        "label": "The Graph",
        "type": "bool",
        "default": True,
        "group": "Data Providers",
        "description": "Enable The Graph for Ethereum mint/burn transfer events (100K queries/mo free)",
        "requires_restart": False,
        "affects_rate_limits": True,
        "rate_limit_rpm": 30,
        "warning_threshold": 0.8,
    },
    "provider_flipside": {
        "label": "Flipside",
        "type": "bool",
        "default": False,
        "key_env": "FLIPSIDE_API_KEY",
        "group": "Data Providers",
        "description": "Enable Flipside SQL for optional holder flow queries (500 query-seconds/mo free)",
        "requires_restart": False,
        "affects_rate_limits": True,
        "rate_limit_rpm": 5,
        "warning_threshold": 0.8,
    },
    "feature_onchain_signals": {
        "label": "On-chain Signals",
        "type": "bool",
        "default": True,
        "group": "Features",
        "description": "Whale flow, holder concentration, mint/burn from free-tier on-chain providers",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "onchain_whale_threshold_usd": {
        "label": "Whale Transfer Threshold (USD)",
        "type": "int",
        "default": 1000000,
        "min": 100000,
        "max": 100000000,
        "group": "Analysis",
        "description": "Minimum transfer size to flag as whale alert (Moralis)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "thegraph_subgraph_url": {
        "label": "The Graph Subgraph URL",
        "type": "str",
        "default": "",
        "group": "Data Collection",
        "description": "Override default Ethereum ERC-20 subgraph endpoint (optional)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "feature_osint_feed": {
        "label": "OSINT Feed (RSS)",
        "type": "bool",
        "default": True,
        "group": "Data Sources",
        "description": "Enable OSINT feed (news, social, blog sources)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_mode": {
        "label": "AI Mode",
        "type": "str",
        "default": "ai_off",
        "key_env": "AI_MODE",
        "choices": ["ai_off", "ai_lite", "ai_full"],
        "group": "AI & Intelligence",
        "description": "AI mode: ai_off, ai_lite, or ai_full",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "api_auth_mode": {
        "label": "API Auth Mode",
        "type": "str",
        "default": "open",
        "key_env": "API_AUTH_MODE",
        "choices": ["open", "key_required"],
        "group": "Security",
        "description": "open = anonymous read OK for intelligence routes; key_required = API key or admin session required. Investigate/alerts/blacklist stay keyed in both modes.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_fallback_provider": {
        "label": "AI Task Fallback Provider ID",
        "type": "str",
        "default": "openrouter",
        "group": "AI & Intelligence",
        "description": "Tier-2 fallback: registered provider id when the per-feature primary fails.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_fallback_model": {
        "label": "AI Fallback Model",
        "type": "str",
        "default": "openai/gpt-4o-mini",
        "group": "AI & Intelligence",
        "description": "Model ID to use on fallback (without provider prefix)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_cache_ttl_seconds": {
        "label": "AI Cache TTL (seconds)",
        "type": "int",
        "default": 3600,
        "min": 60,
        "max": 86400,
        "key_env": "AI_CACHE_TTL_SECONDS",
        "group": "AI & Intelligence",
        "description": "Time to live for AI response cache",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_cache_semantic_enabled": {
        "label": "AI Semantic Cache",
        "type": "bool",
        "default": False,
        "key_env": "AI_CACHE_SEMANTIC_ENABLED",
        "group": "AI & Intelligence",
        "description": "Enable semantic caching — matches similar prompts via text similarity (character trigram Jaccard)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_cache_semantic_threshold": {
        "label": "AI Semantic Cache Threshold",
        "type": "str",
        "default": "0.90",
        "key_env": "AI_CACHE_SEMANTIC_THRESHOLD",
        "group": "AI & Intelligence",
        "description": "Similarity threshold (0.5-1.0) for semantic cache matches",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_cache_max_entries": {
        "label": "AI Cache Max Entries",
        "type": "int",
        "default": 1000,
        "min": 100,
        "max": 10000,
        "key_env": "AI_CACHE_MAX_ENTRIES",
        "group": "AI & Intelligence",
        "description": "Maximum number of entries in the in-memory AI response cache",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_cache_max_semantic_entries": {
        "label": "AI Semantic Cache Max Entries",
        "type": "int",
        "default": 200,
        "min": 10,
        "max": 2000,
        "group": "AI & Intelligence",
        "description": "Maximum number of entries in the semantic similarity cache",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_cache_ttl_market_narrative": {
        "label": "AI Market Narrative Cache TTL",
        "type": "int",
        "default": 3000,
        "min": 60,
        "max": 86400,
        "key_env": "AI_CACHE_TTL_MARKET_NARRATIVE",
        "group": "AI & Intelligence",
        "description": "Time to live for Market Narrative AI responses (seconds)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "feature_ai_summary": {
        "label": "AI Summary Card",
        "type": "bool",
        "default": True,
        "group": "AI & Intelligence",
        "description": "Show AI-generated stablecoin summaries on dashboard",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "feature_ai_narrative": {
        "label": "AI Market Narrative",
        "type": "bool",
        "default": True,
        "group": "AI & Intelligence",
        "description": "Enable AI market narrative on Signal tab",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_prompt_market_narrative_user": {
        "label": "Narrative Prompt Template",
        "type": "str",
        "default": "",
        "group": "AI & Intelligence",
        "description": "Optional user prompt template for market_narrative (empty = built-in default)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_prompt_market_narrative_system": {
        "label": "Narrative System Prompt",
        "type": "str",
        "default": "",
        "group": "AI & Intelligence",
        "description": "Optional system prompt for market_narrative (empty = built-in default)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "feature_ai_explain": {
        "label": "AI Risk Explanation",
        "type": "bool",
        "default": True,
        "group": "AI & Intelligence",
        "description": "Enable AI risk explanations for dashboard signals",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "feature_ai_insights": {
        "label": "AI Multi-Asset Insights",
        "type": "bool",
        "default": True,
        "group": "AI & Intelligence",
        "description": "Enable AI insights in asset comparison view",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    # Per-feature model overrides
    "ai_model_risk_explain": {
        "label": "Risk Explain Model",
        "type": "str",
        "default": "ollama_cloud:ministral-3:8b-cloud",
        "group": "AI & Intelligence",
        "description": "Model for risk explanation (format: provider:model_id)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_model_market_narrative": {
        "label": "Market Narrative Model",
        "type": "str",
        "default": "ollama_cloud:ministral-3:8b-cloud",
        "group": "AI & Intelligence",
        "description": "Model for market narrative (format: provider:model_id)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_model_insight_summary": {
        "label": "Insight Summary Model",
        "type": "str",
        "default": "ollama_cloud:ministral-3:8b-cloud",
        "group": "AI & Intelligence",
        "description": "Model for insight summary (format: provider:model_id)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_model_market_overview": {
        "label": "Market Overview Model",
        "type": "str",
        "default": "ollama_cloud:ministral-3:8b-cloud",
        "group": "AI & Intelligence",
        "description": "Model for market overview (format: provider:model_id)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_model_anomaly_investigation": {
        "label": "Anomaly Investigation Model",
        "type": "str",
        "default": "ollama_cloud:ministral-3:8b-cloud",
        "group": "AI & Intelligence",
        "description": "Model for anomaly investigation (format: provider:model_id)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_model_predictive": {
        "label": "Predictive Analytics Model",
        "type": "str",
        "default": "ollama_cloud:ministral-3:8b-cloud",
        "group": "AI & Intelligence",
        "description": "Model for predictive analytics (format: provider:model_id)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "enable_predictive": {
        "label": "Predictive Analytics",
        "type": "bool",
        "default": True,
        "group": "AI & Intelligence",
        "description": "Enable predictive analytics (depeg probability, regime detection)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_require_token": {
        "label": "Require Admin Token for AI",
        "type": "bool",
        "default": False,
        "group": "AI & Intelligence",
        "description": (
            "When true, AI explain/narrative routes require admin session or X-Admin-Token. "
            "Default false for trusted LAN/OSS. Enable for any internet-facing deploy to limit cost abuse."
        ),
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "alert_email_enabled": {
        "label": "Email Alerts",
        "type": "bool",
        "default": False,
        "group": "Notifications",
        "description": "Enable email alert delivery",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "alert_email_from": {
        "label": "Email From Address",
        "type": "str",
        "default": "",
        "group": "Notifications",
        "description": "Sender email address for alerts",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "alert_email_to": {
        "label": "Email To Address",
        "type": "str",
        "default": "",
        "group": "Notifications",
        "description": "Recipient email address for alerts",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "refresh_core_seconds": {
        "label": "Core data refresh interval",
        "type": "int",
        "default": 300,
        "min": 60,
        "max": 3600,
        "group": "Performance",
        "description": "Interval between core data refreshes (seconds)",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "refresh_osint_minutes": {
        "label": "OSINT feed refresh interval",
        "type": "int",
        "default": 60,
        "min": 15,
        "max": 1440,
        "group": "Performance",
        "description": "Interval between OSINT feed refreshes (minutes)",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "secret_tavily_api_key": {
        "label": "Tavily API Key",
        "type": "secret",
        "default": "",
        "key_env": "TAVILY_API_KEY",
        "group": "API Keys",
        "description": "Tavily search (primary). Presence + Exa/Tavily enables scheduled web context when AI mode is on.",
        "requires_restart": False,
        "affects_rate_limits": False,
        "provider_metadata": {"name": "Tavily", "tier": "freemium"},
    },
    "secret_exa_api_key": {
        "label": "Exa API Key",
        "type": "secret",
        "default": "",
        "key_env": "EXA_API_KEY",
        "group": "API Keys",
        "description": "Exa search (secondary). Opt-in for web search together with or instead of Tavily.",
        "requires_restart": False,
        "affects_rate_limits": False,
        "provider_metadata": {"name": "Exa", "tier": "freemium"},
    },
    "secret_ollama_api_key": {
        "label": "Ollama API Key",
        "type": "secret",
        "default": "",
        "key_env": "OLLAMA_API_KEY",
        "group": "API Keys",
        "description": "Ollama Cloud LLM + web_search 3rd fallback only when Tavily/Exa opt-in is present",
        "requires_restart": False,
        "affects_rate_limits": False,
        "provider_metadata": {
            "name": "Ollama Cloud",
            "tier": "cloud",
            "models": ["ministral-3:8b-cloud", "qwen-2.5-7b-cloud"],
            "max_tokens": 4096,
            "cost_per_million_tokens": 0.15,
            "free_tier_calls": 0,
            "rate_limit_rpm": 60,
        },
    },
    "secret_openrouter_api_key": {
        "label": "OpenRouter API Key",
        "type": "secret",
        "default": "",
        "key_env": "OPENROUTER_API_KEY",
        "group": "API Keys",
        "description": "API key for OpenRouter inference",
        "requires_restart": False,
        "affects_rate_limits": False,
        "provider_metadata": {
            "name": "OpenRouter",
            "tier": "cloud",
            "models": ["openai/gpt-4o-mini", "meta-llama/llama-3.1-8b-instruct", "google/gemini-pro-1.5", "mistralai/mistral-7b-instruct"],
            "max_tokens": 4096,
            "cost_per_million_tokens": 0.6,
            "free_tier_calls": 1000,
            "rate_limit_rpm": 20,
        },
    },
    "secret_moralis_api_key": {
        "label": "Moralis API Key",
        "type": "secret",
        "default": "",
        "key_env": "MORALIS_API_KEY",
        "group": "API Keys",
        "description": "Moralis API key — holder concentration + large transfers (40K CU/day free)",
        "requires_restart": False,
        "affects_rate_limits": False,
        "provider_metadata": {
            "name": "Moralis",
            "tier": "freemium",
            "free_tier_calls": 40000,
            "rate_limit_rpm": 20,
        },
    },
    "secret_flipside_api_key": {
        "label": "Flipside API Key",
        "type": "secret",
        "default": "",
        "key_env": "FLIPSIDE_API_KEY",
        "group": "API Keys",
        "description": "Flipside API key — optional holder flow SQL (500 query-seconds/mo free)",
        "requires_restart": False,
        "affects_rate_limits": False,
        "provider_metadata": {
            "name": "Flipside",
            "tier": "free",
            "free_tier_calls": 500,
        },
    },
    "secret_alchemy_api_key": {
        "label": "Alchemy API Key",
        "type": "secret",
        "default": "",
        "key_env": "ALCHEMY_API_KEY",
        "group": "API Keys",
        "description": "Alchemy RPC fallback when CHAINLINK_RPC_URL unset (30M CU/mo free)",
        "requires_restart": False,
        "affects_rate_limits": False,
        "provider_metadata": {
            "name": "Alchemy",
            "tier": "freemium",
            "free_tier_calls": 30000000,
        },
    },
    "secret_thegraph_api_key": {
        "label": "The Graph API Key",
        "type": "secret",
        "default": "",
        "key_env": "THEGRAPH_API_KEY",
        "group": "API Keys",
        "description": "Optional The Graph gateway API key (100K queries/mo free)",
        "requires_restart": False,
        "affects_rate_limits": False,
        "provider_metadata": {
            "name": "The Graph",
            "tier": "free",
            "free_tier_calls": 100000,
            "rate_limit_rpm": 30,
        },
    },
    "secret_etherscan_api_key": {
        "label": "Etherscan API Key",
        "type": "secret",
        "default": "",
        "key_env": "ETHERSCAN_API_KEY",
        "group": "API Keys",
        "description": "API key for Etherscan",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "fred_api_key": {
        "label": "FRED API Key",
        "type": "secret",
        "default": "",
        "key_env": "FRED_API_KEY",
        "group": "API Keys",
        "description": "API key for FRED (Federal Reserve Economic Data)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "webhook_enabled": {
        "label": "Webhook Alerts Enabled",
        "type": "bool",
        "default": False,
        "group": "Notifications",
        "description": "Primary Sprint 5 signed webhook system (HMAC): enable dispatch of qualifying signal events via webhook_dispatcher on event flush.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "webhook_url": {
        "label": "Alert Webhook URL",
        "type": "str",
        "default": "",
        "group": "Notifications",
        "description": "Primary Sprint 5 signed webhook endpoint (HMAC SHA-256). Canonical HTTPS URL for outbound alert event POSTs (Zapier, n8n, Pabbly, custom).",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "webhook_signing_secret": {
        "label": "Webhook Signing Secret",
        "type": "secret",
        "default": "",
        "group": "Notifications",
        "description": "Primary Sprint 5 signed webhook system (HMAC): secret for X-Webhook-Signature-256 header verification",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "webhook_min_severity": {
        "label": "Webhook Min Severity",
        "type": "str",
        "default": "warning",
        "group": "Notifications",
        "description": "Primary Sprint 5 signed webhook system: minimum event severity to dispatch (info, warning, or critical)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "webhook_timeout_seconds": {
        "label": "Webhook Timeout (seconds)",
        "type": "int",
        "default": 10,
        "min": 3,
        "max": 60,
        "group": "Notifications",
        "description": "Primary Sprint 5 signed webhook system: HTTP timeout for delivery attempts",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "bluechip_api_key": {
        "label": "Bluechip API Key",
        "type": "secret",
        "default": "",
        "key_env": "BLUECHIP_API_KEY",
        "group": "API Keys",
        "description": "Optional API key for Bluechip SMIDGE ratings",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "anomaly_contamination_override": {
        "label": "Anomaly Contamination Override",
        "type": "float",
        "default": 0.0,
        "min": 0.0,
        "max": 0.5,
        "group": "Analysis",
        "description": "Operator override for IsolationForest contamination (0 = auto per asset age)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    # --- V4 Data Source Toggles ---
    "coinglass_enabled": {
        "label": "Coinglass Funding Rates",
        "type": "bool",
        "default": False,
        "group": "V4 Data Sources",
        "description": "Enable ETH perpetual funding rate polling from Coinglass (requires API key)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "coinglass_api_key": {
        "label": "Coinglass API Key",
        "type": "secret",
        "default": "",
        "key_env": "COINGLASS_API_KEY",
        "group": "API Keys",
        "description": "API key for Coinglass perpetual funding rate data (free tier: 10 req/min, 1000/mo)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ethena_enabled": {
        "label": "Ethena Plugin",
        "type": "bool",
        "default": True,
        "group": "V4 Data Sources",
        "description": "Fetch USDe/sUSDe reserve fund data and yields from Ethena API",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "sky_protocol_enabled": {
        "label": "Sky Protocol Plugin",
        "type": "bool",
        "default": True,
        "group": "V4 Data Sources",
        "description": "Fetch DAI/USDS/sUSDS collateral data from Sky API",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "liquity_enabled": {
        "label": "Liquity Plugin",
        "type": "bool",
        "default": True,
        "group": "V4 Data Sources",
        "description": "Fetch LUSD protocol stats from Liquity v1 API (auto-disables on 404)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "aave_enabled": {
        "label": "Aave Plugin",
        "type": "bool",
        "default": True,
        "group": "V4 Data Sources",
        "description": "Fetch GHO supply/borrow/utilization data from Aave API",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ondo_enabled": {
        "label": "Ondo Plugin",
        "type": "bool",
        "default": True,
        "group": "V4 Data Sources",
        "description": "Fetch USDY NAV/supply/APY from Ondo Finance API",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "blacklist_monitor_enabled": {
        "label": "Blacklist Monitor",
        "type": "bool",
        "default": True,
        "group": "V4 Data Sources",
        "description": "Monitor USDT/USDC/PYUSD issuer freeze events on Ethereum and Tron",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "blacklist_poll_interval_seconds": {
        "label": "Blacklist Poll Interval (s)",
        "type": "int",
        "default": 300,
        "min": 60,
        "max": 3600,
        "group": "V4 Data Sources",
        "description": "Polling interval for issuer blacklist/freeze event monitoring",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "funding_rate_poll_interval_seconds": {
        "label": "Funding Rate Poll Interval (s)",
        "type": "int",
        "default": 900,
        "min": 900,
        "max": 1800,
        "group": "V4 Data Sources",
        "description": "Polling interval for perpetual funding rate data (Coinglass free tier: 15–30 min recommended)",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    # --- V4 External Intelligence Webhook ---
    "external_intel_webhook_enabled": {
        "label": "External Intel Webhook",
        "type": "bool",
        "default": False,
        "group": "V4 Intelligence",
        "description": "Enable push-based intelligence webhook for pre-classified stablecoin articles",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "external_intel_webhook_secret": {
        "label": "External Intel Webhook Secret",
        "type": "secret",
        "default": "",
        "key_env": "EXTERNAL_INTEL_WEBHOOK_SECRET",
        "group": "V4 Intelligence",
        "description": "Shared secret for external intelligence webhook authentication",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "external_intel_auth_mode": {
        "label": "Intel Webhook Auth Mode",
        "type": "str",
        "default": "secret_header",
        "group": "V4 Intelligence",
        "description": "Authentication mode: secret_header or hmac_sha256",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "external_intel_secret_header_name": {
        "label": "Intel Webhook Header Name",
        "type": "str",
        "default": "X-Intel-Secret",
        "group": "V4 Intelligence",
        "description": "HTTP header name for shared-secret auth mode",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "external_intel_field_map_json": {
        "label": "Intel Webhook Field Map",
        "type": "str",
        "default": "{\"title\":\"title\",\"signal\":\"signal\",\"summary\":\"summary\",\"url\":\"url\",\"published_at\":\"publishedAt\",\"source_domain\":\"source.domain\"}",
        "group": "V4 Intelligence",
        "description": "JSON mapping of incoming payload keys to internal fields (title, signal, summary, url, published_at, source_domain)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "external_intel_min_process_signal": {
        "label": "Intel Min Signal Level",
        "type": "str",
        "default": "INFO",
        "group": "V4 Intelligence",
        "description": "Minimum signal level to process (INFO, WARNING, or CRITICAL). Lower levels are dropped.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    # --- V4 ONNX Model Paths ---
    "onnx_depeg_model_path": {
        "label": "ONNX Depeg Model Path",
        "type": "str",
        "default": "",
        "key_env": "ONNX_DEPEG_MODEL_PATH",
        "group": "V4 ML Models",
        "description": "Path to V3/V4 depeg probability ONNX model (env fallback: ONNX_DEPEG_MODEL_PATH). V4 auto-resolves type-specific models from backend/ml_models/.",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "onnx_funding_model_path": {
        "label": "ONNX Funding Regime Model Path",
        "type": "str",
        "default": "",
        "key_env": "ONNX_FUNDING_MODEL_PATH",
        "group": "V4 ML Models",
        "description": "Path to funding regime classifier ONNX model (env fallback: ONNX_FUNDING_MODEL_PATH).",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "onnx_yield_model_path": {
        "label": "ONNX Yield Sustainability Model Path",
        "type": "str",
        "default": "",
        "key_env": "ONNX_YIELD_MODEL_PATH",
        "group": "V4 ML Models",
        "description": "Path to yield sustainability ONNX model (env fallback: ONNX_YIELD_MODEL_PATH).",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    # --- Presets (Phase 1) ---
    "retention_preset": {
        "label": "Retention Preset",
        "type": "str",
        "default": "standard",
        "choices": ["minimal", "standard", "research", "custom"],
        "group": "Data & Assets",
        "description": "minimal/standard/research apply all retention_*_days; custom keeps per-table values.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "anomaly_sensitivity": {
        "label": "Anomaly Sensitivity",
        "type": "str",
        "default": "normal",
        "choices": ["low", "normal", "high"],
        "group": "Analysis",
        "description": "Maps to z-score/CUSUM thresholds (low=fewer alerts, high=more).",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    # --- Display & Access (Phase 2 keys registered in Phase 1) ---
    "public_history_hours": {
        "label": "Public History Window (hours)",
        "type": "int",
        "default": 24,
        "min": 1,
        "max": 8760,
        "group": "Display & Access",
        "description": "Max lookback for unauthenticated /api/public/* reads.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "public_tabs_enabled": {
        "label": "Public Tabs",
        "type": "str",
        "default": "signal,market,intel",
        "group": "Display & Access",
        "description": "Comma-separated tab ids visible without admin login.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "public_export_enabled": {
        "label": "Public Export",
        "type": "bool",
        "default": False,
        "group": "Display & Access",
        "description": "Allow CSV/JSON export for anonymous visitors.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "public_show_forensics": {
        "label": "Public Forensics Tab",
        "type": "bool",
        "default": False,
        "group": "Display & Access",
        "description": "Show Forensics tab to anonymous visitors.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "public_deterministic_why": {
        "label": "Public Deterministic Why",
        "type": "bool",
        "default": True,
        "group": "Display & Access",
        "description": "Show basic STATUS/why line from metrics without LLM.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "demo_mode_enabled": {
        "label": "Demo Mode",
        "type": "bool",
        "default": False,
        "group": "Display & Access",
        "description": "Temporarily widen public history for sales demos.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "demo_history_hours": {
        "label": "Demo History Window (hours)",
        "type": "int",
        "default": 168,
        "min": 1,
        "max": 8760,
        "group": "Display & Access",
        "description": "Public lookback while demo mode is active.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "demo_mode_until": {
        "label": "Demo Mode Until (ISO UTC)",
        "type": "str",
        "default": "",
        "group": "Display & Access",
        "description": "When set, demo mode auto-expires after this timestamp.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "intelligence_api_enabled": {
        "label": "Intelligence API Enabled",
        "type": "bool",
        "default": True,
        "group": "Display & Access",
        "description": "Master switch for keyed intelligence API access.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "alert_email_event_types": {
        "label": "Email Event Types",
        "type": "str",
        "default": "[]",
        "group": "Notifications",
        "description": "JSON array of event categories that trigger SMTP (empty = none until configured).",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "alert_email_min_severity": {
        "label": "Email Min Severity",
        "type": "str",
        "default": "warning",
        "choices": ["info", "warning", "critical"],
        "group": "Notifications",
        "description": "Minimum severity for SMTP alert delivery.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_default_fallback_provider": {
        "label": "Global AI Fallback Provider ID",
        "type": "str",
        "default": "",
        "group": "AI & Intelligence",
        "description": "Tier-3 fallback: registered provider id used when primary and task fallback fail.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_default_fallback_model_id": {
        "label": "Global AI Fallback Model ID",
        "type": "str",
        "default": "",
        "group": "AI & Intelligence",
        "description": "Tier-3 fallback model id (free text) for all AI tasks.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
}

# Export the settings registry
__all__ = ["_DEFAULT_SETTINGS"]