"""Settings registry - contains all default settings definitions."""

from typing import Any, Dict

# Default settings registry - moved from providers/settings.py to reduce file size
_DEFAULT_SETTINGS: Dict[str, Dict[str, Any]] = {
    "cors_origins": {
        "label": "CORS Origins",
        "type": "str",
        "default": "http://localhost:3000,http://localhost",
        "group": "Security",
        "description": "Allowed CORS origins (comma-separated). Use '*' only for development.",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "feature_nlp_sentiment": {
        "label": "NLP Sentiment",
        "type": "bool",
        "default": True,
        "key_env": "ENABLE_NLP_SENTIMENT",
        "group": "Features",
        "description": "Enable NLP sentiment analysis (Settings is the source of truth; env is ignored in UI)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "asset_enable_overrides": {
        "label": "Asset Enable Overrides",
        "type": "str",
        "default": "{}",
        "group": "Data & Assets",
        "description": "JSON map of symbol→bool overrides on top of config/assets.json (e.g. {\"USDe\": true})",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "llm_extract_cache_ttl": {
        "label": "LLM Extract Cache TTL",
        "type": "int",
        "default": 3600,
        "min": 60,
        "max": 86400,
        "group": "Cache",
        "description": "Cache TTL for LLM data extraction (seconds)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "openrouter_free_model": {
        "label": "OpenRouter Free Model",
        "type": "str",
        "default": "gpt-4o-mini",
        "group": "AI Providers",
        "description": "Free tier model for OpenRouter",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "anomaly_std_floor": {
        "label": "Anomaly Std Floor",
        "type": "float",
        "default": 0.01,
        "group": "Analysis",
        "description": "Minimum standard deviation floor for anomaly detection",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "sentiment_max_articles_per_batch": {
        "label": "Sentiment Max Articles",
        "type": "int",
        "default": 10,
        "min": 10,
        "max": 200,
        "group": "Analysis",
        "description": "Max articles per sentiment batch",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "alert_discord_webhook": {
        "label": "Discord Webhook URL",
        "type": "str",
        "default": "",
        "group": "Notifications",
        "description": "Discord webhook URL for alerts",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "alert_smtp_host": {
        "label": "SMTP Host",
        "type": "str",
        "default": "",
        "key_env": "ALERT_SMTP_HOST",
        "group": "Notifications",
        "description": "SMTP server host",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "alert_smtp_port": {
        "label": "SMTP Port",
        "type": "int",
        "default": 587,
        "min": 1,
        "max": 65535,
        "group": "Notifications",
        "description": "SMTP server port",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "alert_smtp_user": {
        "label": "SMTP User",
        "type": "str",
        "default": "",
        "key_env": "ALERT_SMTP_USER",
        "group": "Notifications",
        "description": "SMTP username",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "alert_smtp_pass": {
        "label": "SMTP Password",
        "type": "secret",
        "default": "",
        "key_env": "ALERT_SMTP_PASS",
        "secret": True,
        "group": "Notifications",
        "description": "SMTP password",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "allow_backfill": {
        "label": "Allow Backfill",
        "type": "bool",
        "default": False,
        "group": "Data Collection",
        "description": "Allow historical data backfill",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "enable_redis_cache": {
        "label": "Enable Redis Cache",
        "type": "bool",
        "default": False,
        "key_env": "ENABLE_REDIS_CACHE",
        "group": "Cache",
        "description": "Enable Redis caching layer",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "enable_chainlink": {
        "label": "Enable Chainlink",
        "type": "bool",
        "default": False,
        "key_env": "ENABLE_CHAINLINK",
        "group": "Data Collection",
        "description": "Enable Chainlink oracle data",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "enable_dynamic_chains": {
        "label": "Enable Dynamic Chains",
        "type": "bool",
        "default": False,
        "group": "Features",
        "description": "Enable dynamic chain discovery",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "feature_multi_user": {
        "label": "Multi-User Mode",
        "type": "bool",
        "default": False,
        "group": "Features",
        "description": "Enable multi-user support",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "provider_defillama": {
        "label": "DefiLlama",
        "type": "bool",
        "default": True,
        "always_active": True,
        "group": "Data Providers",
        "description": "Enable DefiLlama API for stablecoin metrics",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "provider_dexscreener": {
        "label": "DexScreener",
        "type": "bool",
        "default": True,
        "always_active": True,
        "group": "Data Providers",
        "description": "Enable DexScreener API for DEX pool data",
        "requires_restart": False,
        "affects_rate_limits": True,
        "rate_limit_rpm": 120,  # Increased from 60 to 120
        "warning_threshold": 0.8,
    },
    "provider_coingecko": {
        "label": "CoinGecko",
        "type": "bool",
        "default": True,
        "always_active": True,
        "group": "Data Providers",
        "description": "Enable CoinGecko API for price data",
        "requires_restart": False,
        "affects_rate_limits": True,
        "rate_limit_rpm": 100,  # Increased from 50 to 100
        "warning_threshold": 0.8,
    },
    "provider_coinmarketcap": {
        "label": "CoinMarketCap",
        "type": "bool",
        "default": False,
        "key_env": "CMC_API_KEY",
        "group": "Data Providers",
        "description": "Enable CoinMarketCap API (requires API key)",
        "requires_restart": False,
        "affects_rate_limits": True,
    },
    "provider_moralis": {
        "label": "Moralis",
        "type": "bool",
        "default": False,
        "key_env": "MORALIS_API_KEY",
        "group": "Data Providers",
        "description": "Enable Moralis API for holder concentration and whale transfers (40K CU/day free)",
        "requires_restart": False,
        "affects_rate_limits": True,
        "rate_limit_rpm": 20,
        "warning_threshold": 0.8,
    },
    "provider_thegraph": {
        "label": "The Graph",
        "type": "bool",
        "default": True,
        "group": "Data Providers",
        "description": "Enable The Graph for Ethereum mint/burn transfer events (100K queries/mo free)",
        "requires_restart": False,
        "affects_rate_limits": True,
        "rate_limit_rpm": 30,
        "warning_threshold": 0.8,
    },
    "provider_flipside": {
        "label": "Flipside",
        "type": "bool",
        "default": False,
        "key_env": "FLIPSIDE_API_KEY",
        "group": "Data Providers",
        "description": "Enable Flipside SQL for optional holder flow queries (500 query-seconds/mo free)",
        "requires_restart": False,
        "affects_rate_limits": True,
        "rate_limit_rpm": 5,
        "warning_threshold": 0.8,
    },
    "feature_onchain_signals": {
        "label": "On-chain Signals",
        "type": "bool",
        "default": True,
        "group": "Features",
        "description": "Whale flow, holder concentration, mint/burn from free-tier on-chain providers",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "onchain_whale_threshold_usd": {
        "label": "Whale Transfer Threshold (USD)",
        "type": "int",
        "default": 1000000,
        "min": 100000,
        "max": 100000000,
        "group": "Analysis",
        "description": "Minimum transfer size to flag as whale alert (Moralis)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "thegraph_subgraph_url": {
        "label": "The Graph Subgraph URL",
        "type": "str",
        "default": "",
        "group": "Data Collection",
        "description": "Override default Ethereum ERC-20 subgraph endpoint (optional)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "feature_osint_feed": {
        "label": "OSINT Feed (RSS)",
        "type": "bool",
        "default": True,
        "group": "Data Sources",
        "description": "Enable OSINT feed (news, social, blog sources)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_mode": {
        "label": "AI Mode",
        "type": "str",
        "default": "ai_off",
        "key_env": "AI_MODE",
        "choices": ["ai_off", "ai_lite", "ai_full"],
        "group": "AI & Intelligence",
        "description": "AI mode: ai_off, ai_lite, or ai_full",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "api_auth_mode": {
        "label": "API Auth Mode",
        "type": "str",
        "default": "open",
        "key_env": "API_AUTH_MODE",
        "choices": ["open", "key_required"],
        "group": "Security",
        "description": "open = anonymous read OK for intelligence routes; key_required = API key or admin session required. Investigate/alerts/blacklist stay keyed in both modes.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_daily_token_budget": {
        "label": "AI Daily Token Budget",
        "type": "int",
        "default": 50000,
        "key_env": "AI_DAILY_TOKEN_BUDGET",
        "min": 1000,
        "max": 500000,
        "group": "AI & Intelligence",
        "description": "Maximum tokens to consume per day across all AI providers",
        "requires_restart": False,
        "affects_rate_limits": True,
        "warning_threshold": 0.8,
    },
    "ai_provider_priority": {
        "label": "AI Provider Priority",
        "type": "str",
        "default": '["groq","ollama_cloud","cloudflare","openrouter_free","openrouter_paid"]',
        "group": "AI & Intelligence",
        "description": "Ordered priority list of AI providers (JSON array). Tiers: cache → groq → ollama_cloud → cloudflare → openrouter_free → openrouter_paid",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_cache_ttl_seconds": {
        "label": "AI Cache TTL (seconds)",
        "type": "int",
        "default": 3600,
        "min": 60,
        "max": 86400,
        "key_env": "AI_CACHE_TTL_SECONDS",
        "group": "AI & Intelligence",
        "description": "Time to live for AI response cache",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_cache_semantic_enabled": {
        "label": "AI Semantic Cache",
        "type": "bool",
        "default": False,
        "key_env": "AI_CACHE_SEMANTIC_ENABLED",
        "group": "AI & Intelligence",
        "description": "Enable semantic caching — matches similar prompts via text similarity (character trigram Jaccard)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_cache_semantic_threshold": {
        "label": "AI Semantic Cache Threshold",
        "type": "str",
        "default": "0.90",
        "key_env": "AI_CACHE_SEMANTIC_THRESHOLD",
        "group": "AI & Intelligence",
        "description": "Similarity threshold (0.5-1.0) for semantic cache matches",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_cache_max_entries": {
        "label": "AI Cache Max Entries",
        "type": "int",
        "default": 1000,
        "min": 100,
        "max": 10000,
        "key_env": "AI_CACHE_MAX_ENTRIES",
        "group": "AI & Intelligence",
        "description": "Maximum number of entries in the in-memory AI response cache",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_cache_max_semantic_entries": {
        "label": "AI Semantic Cache Max Entries",
        "type": "int",
        "default": 200,
        "min": 10,
        "max": 2000,
        "group": "AI & Intelligence",
        "description": "Maximum number of entries in the semantic similarity cache",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_cache_ttl_market_narrative": {
        "label": "AI Market Narrative Cache TTL",
        "type": "int",
        "default": 3000,
        "min": 60,
        "max": 86400,
        "key_env": "AI_CACHE_TTL_MARKET_NARRATIVE",
        "group": "AI & Intelligence",
        "description": "Time to live for Market Narrative AI responses (seconds)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_web_search": {
        "label": "AI Web Search",
        "type": "bool",
        "default": False,
        "key_env": "AI_WEB_SEARCH",
        "group": "AI & Intelligence",
        "description": "Enable web search for AI features",
        "requires_restart": False,
        "affects_rate_limits": True,
    },
    "ai_web_search_max_results": {
        "label": "AI Web Search Max Results",
        "type": "int",
        "default": 3,
        "min": 1,
        "max": 10,
        "key_env": "AI_WEB_SEARCH_MAX_RESULTS",
        "group": "AI & Intelligence",
        "description": "Maximum number of web search results to fetch per AI query",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "feature_ai_summary": {
        "label": "AI Summary Card",
        "type": "bool",
        "default": True,
        "group": "AI & Intelligence",
        "description": "Show AI-generated stablecoin summaries on dashboard",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "feature_ai_narrative": {
        "label": "AI Market Narrative",
        "type": "bool",
        "default": True,
        "group": "AI & Intelligence",
        "description": "Enable AI market narrative on Signal tab",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_prompt_market_narrative_user": {
        "label": "Narrative Prompt Template",
        "type": "str",
        "default": "",
        "group": "AI & Intelligence",
        "description": "Optional user prompt template for market_narrative (empty = built-in default)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_prompt_market_narrative_system": {
        "label": "Narrative System Prompt",
        "type": "str",
        "default": "",
        "group": "AI & Intelligence",
        "description": "Optional system prompt for market_narrative (empty = built-in default)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    # Per-feature settings for AI summary
    "ai_summary_max_length": {
        "label": "Summary Max Length",
        "type": "int",
        "default": 500,
        "min": 100,
        "max": 2000,
        "group": "AI & Intelligence",
        "description": "Maximum character length for AI-generated summaries",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_summary_detail_level": {
        "label": "Summary Detail Level",
        "type": "str",
        "default": "medium",
        "group": "AI & Intelligence",
        "description": "Level of detail in summaries (low, medium, high)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "feature_ai_explain": {
        "label": "AI Risk Explanation",
        "type": "bool",
        "default": True,
        "group": "AI & Intelligence",
        "description": "Enable AI risk explanations for dashboard signals",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    # Per-feature settings for AI risk explanation
    "ai_explain_max_factors": {
        "label": "Max Risk Factors",
        "type": "int",
        "default": 5,
        "min": 1,
        "max": 10,
        "group": "AI & Intelligence",
        "description": "Maximum number of risk factors to explain per signal",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_explain_confidence_min": {
        "label": "Explanation Confidence Min",
        "type": "float",
        "default": 0.6,
        "min": 0.1,
        "max": 0.99,
        "group": "AI & Intelligence",
        "description": "Minimum confidence level for risk explanations",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "feature_ai_insights": {
        "label": "AI Multi-Asset Insights",
        "type": "bool",
        "default": True,
        "group": "AI & Intelligence",
        "description": "Enable AI insights in asset comparison view",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    # Per-feature settings for AI insights
    "ai_insights_max_assets": {
        "label": "Max Assets in Insights",
        "type": "int",
        "default": 10,
        "min": 2,
        "max": 50,
        "group": "AI & Intelligence",
        "description": "Maximum number of assets to analyze in multi-asset insights",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_insights_correlation_min": {
        "label": "Min Correlation Threshold",
        "type": "float",
        "default": 0.3,
        "min": 0.0,
        "max": 1.0,
        "group": "AI & Intelligence",
        "description": "Minimum correlation coefficient to report relationships",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    # Per-feature model overrides
    "ai_model_risk_explain": {
        "label": "Risk Explain Model",
        "type": "str",
        "default": "",
        "group": "AI & Intelligence",
        "description": "Model to use for risk explanation feature (empty = use provider default)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_model_market_narrative": {
        "label": "Market Narrative Model",
        "type": "str",
        "default": "",
        "group": "AI & Intelligence", 
        "description": "Model to use for market narrative feature (empty = use provider default)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_model_insight_summary": {
        "label": "Insight Summary Model",
        "type": "str",
        "default": "",
        "group": "AI & Intelligence",
        "description": "Model to use for insight summary feature (empty = use provider default)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_model_predictive": {
        "label": "Predictive Analytics Model",
        "type": "str",
        "default": "",
        "group": "AI & Intelligence",
        "description": "Model to use for predictive analytics feature (empty = use provider default)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "enable_predictive": {
        "label": "Predictive Analytics",
        "type": "bool",
        "default": True,
        "group": "AI & Intelligence",
        "description": "Enable predictive analytics (depeg probability, regime detection)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    # Per-feature settings for predictive analytics
    "predictive_enable_depeg": {
        "label": "Enable Depeg Prediction",
        "type": "bool",
        "default": True,
        "group": "AI & Intelligence",
        "description": "Enable depeg probability prediction in predictive analytics",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "predictive_enable_regime": {
        "label": "Enable Regime Detection",
        "type": "bool",
        "default": True,
        "group": "AI & Intelligence",
        "description": "Enable regime state detection in predictive analytics",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "predictive_depeg_horizons": {
        "label": "Depeg Prediction Horizons",
        "type": "str",
        "default": "1h,6h,24h",
        "group": "AI & Intelligence",
        "description": "Comma-separated list of time horizons for depeg probability prediction (1h,6h,24h,7d)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "predictive_confidence_threshold": {
        "label": "Prediction Confidence Threshold",
        "type": "float",
        "default": 0.7,
        "min": 0.1,
        "max": 0.99,
        "group": "AI & Intelligence",
        "description": "Minimum confidence level for predictions to be displayed (0.1-0.99)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ai_require_token": {
        "label": "Require Admin Token for AI",
        "type": "bool",
        "default": False,
        "group": "AI & Intelligence",
        "description": "Require X-Admin-Token header for AI features",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "alert_email_enabled": {
        "label": "Email Alerts",
        "type": "bool",
        "default": False,
        "group": "Notifications",
        "description": "Enable email alert delivery",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "alert_email_from": {
        "label": "Email From Address",
        "type": "str",
        "default": "",
        "group": "Notifications",
        "description": "Sender email address for alerts",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "alert_email_to": {
        "label": "Email To Address",
        "type": "str",
        "default": "",
        "group": "Notifications",
        "description": "Recipient email address for alerts",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "refresh_core_seconds": {
        "label": "Core data refresh interval",
        "type": "int",
        "default": 300,
        "min": 60,
        "max": 3600,
        "group": "Performance",
        "description": "Interval between core data refreshes (seconds)",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "refresh_osint_minutes": {
        "label": "OSINT feed refresh interval",
        "type": "int",
        "default": 60,
        "min": 15,
        "max": 1440,
        "group": "Performance",
        "description": "Interval between OSINT feed refreshes (minutes)",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "secret_ollama_api_key": {
        "label": "Ollama API Key",
        "type": "secret",
        "default": "",
        "key_env": "OLLAMA_API_KEY",
        "group": "API Keys",
        "description": "API key for Ollama Cloud",
        "requires_restart": False,
        "affects_rate_limits": False,
        "provider_metadata": {
            "name": "Ollama Cloud",
            "tier": "cloud",
            "models": ["ministral-3:8b-cloud", "qwen-2.5-7b-cloud"],
            "max_tokens": 4096,
            "cost_per_million_tokens": 0.15,
            "free_tier_calls": 0,
            "rate_limit_rpm": 60,
        },
    },
    "secret_cloudflare_api_token": {
        "label": "Cloudflare API Token",
        "type": "secret",
        "default": "",
        "key_env": "CLOUDFLARE_API_TOKEN",
        "group": "API Keys",
        "description": "API token for Cloudflare Workers AI",
        "requires_restart": False,
        "affects_rate_limits": False,
        "provider_metadata": {
            "name": "Cloudflare Workers AI",
            "tier": "cloud",
            "models": ["@cf/meta/llama-3.1-8b-instruct", "@cf/mistral/mistral-7b-instruct-v0.1"],
            "max_tokens": 4096,
            "cost_per_million_tokens": 0.0,
            "free_tier_calls": 100000,
            "rate_limit_rpm": 50,
        },
    },
    "cloudflare_account_id": {
        "label": "Cloudflare Account ID",
        "type": "str",
        "default": "",
        "group": "AI & Intelligence",
        "description": "Cloudflare account ID for Workers AI (find in dashboard -> Workers AI)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "cloudflare_ai_model": {
        "label": "Cloudflare AI Model",
        "type": "str",
        "default": "@cf/meta/llama-3.1-8b-instruct",
        "group": "AI & Intelligence",
        "description": "Cloudflare Workers AI model name (e.g. @cf/meta/llama-3.1-8b-instruct)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "groq_model": {
        "label": "Groq Model",
        "type": "str",
        "default": "llama-3.1-8b-instant",
        "group": "AI & Intelligence",
        "description": "Groq model name (e.g. llama-3.1-8b-instant)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "secret_groq_api_key": {
        "label": "Groq API Key",
        "type": "secret",
        "default": "",
        "key_env": "GROQ_API_KEY",
        "group": "API Keys",
        "description": "API key for Groq inference",
        "requires_restart": False,
        "affects_rate_limits": False,
        "provider_metadata": {
            "name": "Groq",
            "tier": "cloud",
            "models": ["llama-3.1-8b-instant", "llama-3.1-70b-versatile", "llama3-8b-8192", "llama3-70b-8192", "mixtral-8x7b-32768"],
            "max_tokens": 8192,
            "cost_per_million_tokens": 0.05,
            "free_tier_calls": 0,
            "rate_limit_rpm": 30,
        },
    },
    "ollama_cloud_model": {
        "label": "Ollama Cloud Model",
        "type": "str",
        "default": "ministral-3:8b-cloud",
        "group": "AI & Intelligence",
        "description": "Ollama Cloud model name (e.g. ministral-3:8b-cloud)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "secret_openrouter_api_key": {
        "label": "OpenRouter API Key",
        "type": "secret",
        "default": "",
        "key_env": "OPENROUTER_API_KEY",
        "group": "API Keys",
        "description": "API key for OpenRouter inference",
        "requires_restart": False,
        "affects_rate_limits": False,
        "provider_metadata": {
            "name": "OpenRouter",
            "tier": "cloud",
            "models": ["openai/gpt-4o-mini", "meta-llama/llama-3.1-8b-instruct", "google/gemini-pro-1.5", "mistralai/mistral-7b-instruct"],
            "max_tokens": 4096,
            "cost_per_million_tokens": 0.6,
            "free_tier_calls": 1000,
            "rate_limit_rpm": 20,
        },
    },
    "openrouter_model": {
        "label": "OpenRouter Model",
        "type": "str",
        "default": "openai/gpt-4o-mini",
        "group": "AI & Intelligence",
        "description": "OpenRouter model name (e.g. openai/gpt-4o-mini)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "secret_cmc_api_key": {
        "label": "CoinMarketCap API Key",
        "type": "secret",
        "default": "",
        "key_env": "CMC_API_KEY",
        "group": "API Keys",
        "description": "API key for CoinMarketCap",
        "requires_restart": False,
        "affects_rate_limits": False,
        "provider_metadata": {
            "name": "CoinMarketCap",
            "tier": "free",
            "models": ["cmc"],
            "max_tokens": 0,
            "cost_per_million_tokens": 0.0,
            "free_tier_calls": 333,
            "rate_limit_rpm": 30,
        },
    },
    "secret_moralis_api_key": {
        "label": "Moralis API Key",
        "type": "secret",
        "default": "",
        "key_env": "MORALIS_API_KEY",
        "group": "API Keys",
        "description": "Moralis API key — holder concentration + large transfers (40K CU/day free)",
        "requires_restart": False,
        "affects_rate_limits": False,
        "provider_metadata": {
            "name": "Moralis",
            "tier": "freemium",
            "free_tier_calls": 40000,
            "rate_limit_rpm": 20,
        },
    },
    "secret_flipside_api_key": {
        "label": "Flipside API Key",
        "type": "secret",
        "default": "",
        "key_env": "FLIPSIDE_API_KEY",
        "group": "API Keys",
        "description": "Flipside API key — optional holder flow SQL (500 query-seconds/mo free)",
        "requires_restart": False,
        "affects_rate_limits": False,
        "provider_metadata": {
            "name": "Flipside",
            "tier": "free",
            "free_tier_calls": 500,
        },
    },
    "secret_alchemy_api_key": {
        "label": "Alchemy API Key",
        "type": "secret",
        "default": "",
        "key_env": "ALCHEMY_API_KEY",
        "group": "API Keys",
        "description": "Alchemy RPC fallback when CHAINLINK_RPC_URL unset (30M CU/mo free)",
        "requires_restart": False,
        "affects_rate_limits": False,
        "provider_metadata": {
            "name": "Alchemy",
            "tier": "freemium",
            "free_tier_calls": 30000000,
        },
    },
    "secret_thegraph_api_key": {
        "label": "The Graph API Key",
        "type": "secret",
        "default": "",
        "key_env": "THEGRAPH_API_KEY",
        "group": "API Keys",
        "description": "Optional The Graph gateway API key (100K queries/mo free)",
        "requires_restart": False,
        "affects_rate_limits": False,
        "provider_metadata": {
            "name": "The Graph",
            "tier": "free",
            "free_tier_calls": 100000,
            "rate_limit_rpm": 30,
        },
    },
    "secret_etherscan_api_key": {
        "label": "Etherscan API Key",
        "type": "secret",
        "default": "",
        "key_env": "ETHERSCAN_API_KEY",
        "group": "API Keys",
        "description": "API key for Etherscan",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "fred_api_key": {
        "label": "FRED API Key",
        "type": "secret",
        "default": "",
        "key_env": "FRED_API_KEY",
        "group": "API Keys",
        "description": "API key for FRED (Federal Reserve Economic Data)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "alert_webhook_url": {
        "label": "Webhook URL (legacy rule engine)",
        "type": "str",
        "default": "",
        "group": "Notifications",
        "description": "Legacy rule-engine webhook: used when an alert rule lists the \"webhook\" channel (simple JSON POST, no HMAC). Not the primary delivery path — see webhook_enabled / webhook_url for the signed Sprint 5 system.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "webhook_enabled": {
        "label": "Webhook Alerts Enabled",
        "type": "bool",
        "default": False,
        "group": "Notifications",
        "description": "Primary Sprint 5 signed webhook system (HMAC): enable dispatch of qualifying signal events via webhook_dispatcher on event flush.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "webhook_url": {
        "label": "Alert Webhook URL",
        "type": "str",
        "default": "",
        "group": "Notifications",
        "description": "Primary Sprint 5 signed webhook endpoint (HMAC SHA-256). Canonical HTTPS URL for outbound alert event POSTs (Zapier, n8n, Pabbly, custom).",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "webhook_signing_secret": {
        "label": "Webhook Signing Secret",
        "type": "secret",
        "default": "",
        "group": "Notifications",
        "description": "Primary Sprint 5 signed webhook system (HMAC): secret for X-Webhook-Signature-256 header verification",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "webhook_min_severity": {
        "label": "Webhook Min Severity",
        "type": "str",
        "default": "warning",
        "group": "Notifications",
        "description": "Primary Sprint 5 signed webhook system: minimum event severity to dispatch (info, warning, or critical)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "webhook_timeout_seconds": {
        "label": "Webhook Timeout (seconds)",
        "type": "int",
        "default": 10,
        "min": 3,
        "max": 60,
        "group": "Notifications",
        "description": "Primary Sprint 5 signed webhook system: HTTP timeout for delivery attempts",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "bluechip_api_key": {
        "label": "Bluechip API Key",
        "type": "secret",
        "default": "",
        "key_env": "BLUECHIP_API_KEY",
        "group": "API Keys",
        "description": "Optional API key for Bluechip SMIDGE ratings",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "anomaly_contamination_override": {
        "label": "Anomaly Contamination Override",
        "type": "float",
        "default": 0.0,
        "min": 0.0,
        "max": 0.5,
        "group": "Analysis",
        "description": "Operator override for IsolationForest contamination (0 = auto per asset age)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    # --- V4 Data Source Toggles ---
    "coinglass_enabled": {
        "label": "Coinglass Funding Rates",
        "type": "bool",
        "default": False,
        "group": "V4 Data Sources",
        "description": "Enable ETH perpetual funding rate polling from Coinglass (requires API key)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "coinglass_api_key": {
        "label": "Coinglass API Key",
        "type": "secret",
        "default": "",
        "key_env": "COINGLASS_API_KEY",
        "group": "API Keys",
        "description": "API key for Coinglass perpetual funding rate data (free tier: 10 req/min, 1000/mo)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ethena_enabled": {
        "label": "Ethena Plugin",
        "type": "bool",
        "default": True,
        "group": "V4 Data Sources",
        "description": "Fetch USDe/sUSDe reserve fund data and yields from Ethena API",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "sky_protocol_enabled": {
        "label": "Sky Protocol Plugin",
        "type": "bool",
        "default": True,
        "group": "V4 Data Sources",
        "description": "Fetch DAI/USDS/sUSDS collateral data from Sky API",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "liquity_enabled": {
        "label": "Liquity Plugin",
        "type": "bool",
        "default": True,
        "group": "V4 Data Sources",
        "description": "Fetch LUSD protocol stats from Liquity v1 API (auto-disables on 404)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "aave_enabled": {
        "label": "Aave Plugin",
        "type": "bool",
        "default": True,
        "group": "V4 Data Sources",
        "description": "Fetch GHO supply/borrow/utilization data from Aave API",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "ondo_enabled": {
        "label": "Ondo Plugin",
        "type": "bool",
        "default": True,
        "group": "V4 Data Sources",
        "description": "Fetch USDY NAV/supply/APY from Ondo Finance API",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "blacklist_monitor_enabled": {
        "label": "Blacklist Monitor",
        "type": "bool",
        "default": True,
        "group": "V4 Data Sources",
        "description": "Monitor USDT/USDC/PYUSD issuer freeze events on Ethereum and Tron",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "blacklist_poll_interval_seconds": {
        "label": "Blacklist Poll Interval (s)",
        "type": "int",
        "default": 300,
        "min": 60,
        "max": 3600,
        "group": "V4 Data Sources",
        "description": "Polling interval for issuer blacklist/freeze event monitoring",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "funding_rate_poll_interval_seconds": {
        "label": "Funding Rate Poll Interval (s)",
        "type": "int",
        "default": 300,
        "min": 60,
        "max": 3600,
        "group": "V4 Data Sources",
        "description": "Polling interval for perpetual funding rate data",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    # --- V4 External Intelligence Webhook ---
    "external_intel_webhook_enabled": {
        "label": "External Intel Webhook",
        "type": "bool",
        "default": False,
        "group": "V4 Intelligence",
        "description": "Enable push-based intelligence webhook for pre-classified stablecoin articles",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "external_intel_webhook_secret": {
        "label": "External Intel Webhook Secret",
        "type": "secret",
        "default": "",
        "key_env": "EXTERNAL_INTEL_WEBHOOK_SECRET",
        "group": "V4 Intelligence",
        "description": "Shared secret for external intelligence webhook authentication",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "external_intel_auth_mode": {
        "label": "Intel Webhook Auth Mode",
        "type": "str",
        "default": "secret_header",
        "group": "V4 Intelligence",
        "description": "Authentication mode: secret_header or hmac_sha256",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "external_intel_secret_header_name": {
        "label": "Intel Webhook Header Name",
        "type": "str",
        "default": "X-Intel-Secret",
        "group": "V4 Intelligence",
        "description": "HTTP header name for shared-secret auth mode",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "external_intel_field_map_json": {
        "label": "Intel Webhook Field Map",
        "type": "str",
        "default": "{\"title\":\"title\",\"signal\":\"signal\",\"summary\":\"summary\",\"url\":\"url\",\"published_at\":\"publishedAt\",\"source_domain\":\"source.domain\"}",
        "group": "V4 Intelligence",
        "description": "JSON mapping of incoming payload keys to internal fields (title, signal, summary, url, published_at, source_domain)",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    "external_intel_min_process_signal": {
        "label": "Intel Min Signal Level",
        "type": "str",
        "default": "INFO",
        "group": "V4 Intelligence",
        "description": "Minimum signal level to process (INFO, WARNING, or CRITICAL). Lower levels are dropped.",
        "requires_restart": False,
        "affects_rate_limits": False,
    },
    # --- V4 ONNX Model Paths ---
    "onnx_depeg_model_path": {
        "label": "ONNX Depeg Model Path",
        "type": "str",
        "default": "",
        "key_env": "ONNX_DEPEG_MODEL_PATH",
        "group": "V4 ML Models",
        "description": "Path to V3/V4 depeg probability ONNX model (env fallback: ONNX_DEPEG_MODEL_PATH). V4 auto-resolves type-specific models from backend/ml_models/.",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "onnx_funding_model_path": {
        "label": "ONNX Funding Regime Model Path",
        "type": "str",
        "default": "",
        "key_env": "ONNX_FUNDING_MODEL_PATH",
        "group": "V4 ML Models",
        "description": "Path to funding regime classifier ONNX model (env fallback: ONNX_FUNDING_MODEL_PATH).",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
    "onnx_yield_model_path": {
        "label": "ONNX Yield Sustainability Model Path",
        "type": "str",
        "default": "",
        "key_env": "ONNX_YIELD_MODEL_PATH",
        "group": "V4 ML Models",
        "description": "Path to yield sustainability ONNX model (env fallback: ONNX_YIELD_MODEL_PATH).",
        "requires_restart": True,
        "affects_rate_limits": False,
    },
}

# Export the settings registry
__all__ = ["_DEFAULT_SETTINGS"]